/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StaffProfileRouteImport } from './routes/staff.profile'
import { Route as StaffLeavesRouteImport } from './routes/staff.leaves'
import { Route as StaffAttendanceRouteImport } from './routes/staff.attendance'
import { Route as ManagerTripsRouteImport } from './routes/manager.trips'
import { Route as ManagerTeamRouteImport } from './routes/manager.team'
import { Route as ManagerTasksRouteImport } from './routes/manager.tasks'
import { Route as ManagerProfileRouteImport } from './routes/manager.profile'
import { Route as ManagerCheckRouteImport } from './routes/manager.check'
import { Route as EmployeeTasksRouteImport } from './routes/employee.tasks'
import { Route as EmployeeSettingsRouteImport } from './routes/employee.settings'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee.notifications'
import { Route as EmployeeMessagesRouteImport } from './routes/employee.messages'
import { Route as EmployeeLeavesRouteImport } from './routes/employee.leaves'
import { Route as EmployeeCheckRouteImport } from './routes/employee.check'
import { Route as EmployeeBiometricsRouteImport } from './routes/employee.biometrics'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as AdminTargetsOvertimeRouteImport } from './routes/admin.targets-overtime'
import { Route as AdminShiftsRouteImport } from './routes/admin.shifts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReassignManagersRouteImport } from './routes/admin.reassign-managers'
import { Route as AdminPayrollSettingsRouteImport } from './routes/admin.payroll-settings'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminOrgChartRouteImport } from './routes/admin.org-chart'
import { Route as AdminNotificationPreferencesRouteImport } from './routes/admin.notification-preferences'
import { Route as AdminNetworksRouteImport } from './routes/admin.networks'
import { Route as AdminLeavesRequestsRouteImport } from './routes/admin.leaves-requests'
import { Route as AdminLeavesRouteImport } from './routes/admin.leaves'
import { Route as AdminLatePenaltiesRouteImport } from './routes/admin.late-penalties'
import { Route as AdminKpisRouteImport } from './routes/admin.kpis'
import { Route as AdminHolidaysRouteImport } from './routes/admin.holidays'
import { Route as AdminGeofencingRouteImport } from './routes/admin.geofencing'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminEmployeeAccessRouteImport } from './routes/admin.employee-access'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAllowancesRouteImport } from './routes/admin.allowances'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin.employees.index'
import { Route as AdminEmployeesIdRouteImport } from './routes/admin.employees.$id'
import { Route as ApiPublicCronRunSchedulesRouteImport } from './routes/api/public/cron/run-schedules'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StaffProfileRoute = StaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLeavesRoute = StaffLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StaffRoute,
} as any)
const ManagerTripsRoute = ManagerTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerTasksRoute = ManagerTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerProfileRoute = ManagerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerCheckRoute = ManagerCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeTasksRoute = EmployeeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeMessagesRoute = EmployeeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeLeavesRoute = EmployeeLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeCheckRoute = EmployeeCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeBiometricsRoute = EmployeeBiometricsRouteImport.update({
  id: '/biometrics',
  path: '/biometrics',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => EmployeeRoute,
} as any)
const AdminTargetsOvertimeRoute = AdminTargetsOvertimeRouteImport.update({
  id: '/targets-overtime',
  path: '/targets-overtime',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShiftsRoute = AdminShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReassignManagersRoute = AdminReassignManagersRouteImport.update({
  id: '/reassign-managers',
  path: '/reassign-managers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollSettingsRoute = AdminPayrollSettingsRouteImport.update({
  id: '/payroll-settings',
  path: '/payroll-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgChartRoute = AdminOrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationPreferencesRoute =
  AdminNotificationPreferencesRouteImport.update({
    id: '/notification-preferences',
    path: '/notification-preferences',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNetworksRoute = AdminNetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeavesRequestsRoute = AdminLeavesRequestsRouteImport.update({
  id: '/leaves-requests',
  path: '/leaves-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeavesRoute = AdminLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLatePenaltiesRoute = AdminLatePenaltiesRouteImport.update({
  id: '/late-penalties',
  path: '/late-penalties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpisRoute = AdminKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHolidaysRoute = AdminHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeofencingRoute = AdminGeofencingRouteImport.update({
  id: '/geofencing',
  path: '/geofencing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeeAccessRoute = AdminEmployeeAccessRouteImport.update({
  id: '/employee-access',
  path: '/employee-access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllowancesRoute = AdminAllowancesRouteImport.update({
  id: '/allowances',
  path: '/allowances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const AdminEmployeesIdRoute = AdminEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEmployeesRoute,
} as any)
const ApiPublicCronRunSchedulesRoute =
  ApiPublicCronRunSchedulesRouteImport.update({
    id: '/api/public/cron/run-schedules',
    path: '/api/public/cron/run-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/admin/allowances': typeof AdminAllowancesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/employee-access': typeof AdminEmployeeAccessRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/geofencing': typeof AdminGeofencingRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/late-penalties': typeof AdminLatePenaltiesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/leaves-requests': typeof AdminLeavesRequestsRoute
  '/admin/networks': typeof AdminNetworksRoute
  '/admin/notification-preferences': typeof AdminNotificationPreferencesRoute
  '/admin/org-chart': typeof AdminOrgChartRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/payroll-settings': typeof AdminPayrollSettingsRoute
  '/admin/reassign-managers': typeof AdminReassignManagersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/targets-overtime': typeof AdminTargetsOvertimeRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/biometrics': typeof EmployeeBiometricsRoute
  '/employee/check': typeof EmployeeCheckRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/messages': typeof EmployeeMessagesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/manager/check': typeof ManagerCheckRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/manager/trips': typeof ManagerTripsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/leaves': typeof StaffLeavesRoute
  '/staff/profile': typeof StaffProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/api/public/cron/run-schedules': typeof ApiPublicCronRunSchedulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/allowances': typeof AdminAllowancesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/employee-access': typeof AdminEmployeeAccessRoute
  '/admin/geofencing': typeof AdminGeofencingRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/late-penalties': typeof AdminLatePenaltiesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/leaves-requests': typeof AdminLeavesRequestsRoute
  '/admin/networks': typeof AdminNetworksRoute
  '/admin/notification-preferences': typeof AdminNotificationPreferencesRoute
  '/admin/org-chart': typeof AdminOrgChartRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/payroll-settings': typeof AdminPayrollSettingsRoute
  '/admin/reassign-managers': typeof AdminReassignManagersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/targets-overtime': typeof AdminTargetsOvertimeRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/biometrics': typeof EmployeeBiometricsRoute
  '/employee/check': typeof EmployeeCheckRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/messages': typeof EmployeeMessagesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/manager/check': typeof ManagerCheckRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/manager/trips': typeof ManagerTripsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/leaves': typeof StaffLeavesRoute
  '/staff/profile': typeof StaffProfileRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/api/public/cron/run-schedules': typeof ApiPublicCronRunSchedulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/admin/allowances': typeof AdminAllowancesRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/employee-access': typeof AdminEmployeeAccessRoute
  '/admin/employees': typeof AdminEmployeesRouteWithChildren
  '/admin/geofencing': typeof AdminGeofencingRoute
  '/admin/holidays': typeof AdminHolidaysRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/late-penalties': typeof AdminLatePenaltiesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/leaves-requests': typeof AdminLeavesRequestsRoute
  '/admin/networks': typeof AdminNetworksRoute
  '/admin/notification-preferences': typeof AdminNotificationPreferencesRoute
  '/admin/org-chart': typeof AdminOrgChartRoute
  '/admin/payroll': typeof AdminPayrollRoute
  '/admin/payroll-settings': typeof AdminPayrollSettingsRoute
  '/admin/reassign-managers': typeof AdminReassignManagersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/targets-overtime': typeof AdminTargetsOvertimeRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/biometrics': typeof EmployeeBiometricsRoute
  '/employee/check': typeof EmployeeCheckRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/messages': typeof EmployeeMessagesRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/employee/tasks': typeof EmployeeTasksRoute
  '/manager/check': typeof ManagerCheckRoute
  '/manager/profile': typeof ManagerProfileRoute
  '/manager/tasks': typeof ManagerTasksRoute
  '/manager/team': typeof ManagerTeamRoute
  '/manager/trips': typeof ManagerTripsRoute
  '/staff/attendance': typeof StaffAttendanceRoute
  '/staff/leaves': typeof StaffLeavesRoute
  '/staff/profile': typeof StaffProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/admin/employees/$id': typeof AdminEmployeesIdRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/api/public/cron/run-schedules': typeof ApiPublicCronRunSchedulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/employee'
    | '/manager'
    | '/staff'
    | '/admin/allowances'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/directory'
    | '/admin/employee-access'
    | '/admin/employees'
    | '/admin/geofencing'
    | '/admin/holidays'
    | '/admin/kpis'
    | '/admin/late-penalties'
    | '/admin/leaves'
    | '/admin/leaves-requests'
    | '/admin/networks'
    | '/admin/notification-preferences'
    | '/admin/org-chart'
    | '/admin/payroll'
    | '/admin/payroll-settings'
    | '/admin/reassign-managers'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/targets-overtime'
    | '/employee/attendance'
    | '/employee/biometrics'
    | '/employee/check'
    | '/employee/leaves'
    | '/employee/messages'
    | '/employee/notifications'
    | '/employee/settings'
    | '/employee/tasks'
    | '/manager/check'
    | '/manager/profile'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/trips'
    | '/staff/attendance'
    | '/staff/leaves'
    | '/staff/profile'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/staff/'
    | '/admin/employees/$id'
    | '/admin/employees/'
    | '/api/public/cron/run-schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/allowances'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/directory'
    | '/admin/employee-access'
    | '/admin/geofencing'
    | '/admin/holidays'
    | '/admin/kpis'
    | '/admin/late-penalties'
    | '/admin/leaves'
    | '/admin/leaves-requests'
    | '/admin/networks'
    | '/admin/notification-preferences'
    | '/admin/org-chart'
    | '/admin/payroll'
    | '/admin/payroll-settings'
    | '/admin/reassign-managers'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/targets-overtime'
    | '/employee/attendance'
    | '/employee/biometrics'
    | '/employee/check'
    | '/employee/leaves'
    | '/employee/messages'
    | '/employee/notifications'
    | '/employee/settings'
    | '/employee/tasks'
    | '/manager/check'
    | '/manager/profile'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/trips'
    | '/staff/attendance'
    | '/staff/leaves'
    | '/staff/profile'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/staff'
    | '/admin/employees/$id'
    | '/admin/employees'
    | '/api/public/cron/run-schedules'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/employee'
    | '/manager'
    | '/staff'
    | '/admin/allowances'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/contracts'
    | '/admin/directory'
    | '/admin/employee-access'
    | '/admin/employees'
    | '/admin/geofencing'
    | '/admin/holidays'
    | '/admin/kpis'
    | '/admin/late-penalties'
    | '/admin/leaves'
    | '/admin/leaves-requests'
    | '/admin/networks'
    | '/admin/notification-preferences'
    | '/admin/org-chart'
    | '/admin/payroll'
    | '/admin/payroll-settings'
    | '/admin/reassign-managers'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/targets-overtime'
    | '/employee/attendance'
    | '/employee/biometrics'
    | '/employee/check'
    | '/employee/leaves'
    | '/employee/messages'
    | '/employee/notifications'
    | '/employee/settings'
    | '/employee/tasks'
    | '/manager/check'
    | '/manager/profile'
    | '/manager/tasks'
    | '/manager/team'
    | '/manager/trips'
    | '/staff/attendance'
    | '/staff/leaves'
    | '/staff/profile'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/staff/'
    | '/admin/employees/$id'
    | '/admin/employees/'
    | '/api/public/cron/run-schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  ApiPublicCronRunSchedulesRoute: typeof ApiPublicCronRunSchedulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/profile': {
      id: '/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof StaffProfileRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/leaves': {
      id: '/staff/leaves'
      path: '/leaves'
      fullPath: '/staff/leaves'
      preLoaderRoute: typeof StaffLeavesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/attendance': {
      id: '/staff/attendance'
      path: '/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/manager/trips': {
      id: '/manager/trips'
      path: '/trips'
      fullPath: '/manager/trips'
      preLoaderRoute: typeof ManagerTripsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/tasks': {
      id: '/manager/tasks'
      path: '/tasks'
      fullPath: '/manager/tasks'
      preLoaderRoute: typeof ManagerTasksRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/profile': {
      id: '/manager/profile'
      path: '/profile'
      fullPath: '/manager/profile'
      preLoaderRoute: typeof ManagerProfileRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/check': {
      id: '/manager/check'
      path: '/check'
      fullPath: '/manager/check'
      preLoaderRoute: typeof ManagerCheckRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/tasks': {
      id: '/employee/tasks'
      path: '/tasks'
      fullPath: '/employee/tasks'
      preLoaderRoute: typeof EmployeeTasksRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/settings': {
      id: '/employee/settings'
      path: '/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/messages': {
      id: '/employee/messages'
      path: '/messages'
      fullPath: '/employee/messages'
      preLoaderRoute: typeof EmployeeMessagesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/leaves': {
      id: '/employee/leaves'
      path: '/leaves'
      fullPath: '/employee/leaves'
      preLoaderRoute: typeof EmployeeLeavesRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/check': {
      id: '/employee/check'
      path: '/check'
      fullPath: '/employee/check'
      preLoaderRoute: typeof EmployeeCheckRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/biometrics': {
      id: '/employee/biometrics'
      path: '/biometrics'
      fullPath: '/employee/biometrics'
      preLoaderRoute: typeof EmployeeBiometricsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/admin/targets-overtime': {
      id: '/admin/targets-overtime'
      path: '/targets-overtime'
      fullPath: '/admin/targets-overtime'
      preLoaderRoute: typeof AdminTargetsOvertimeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shifts': {
      id: '/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminShiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reassign-managers': {
      id: '/admin/reassign-managers'
      path: '/reassign-managers'
      fullPath: '/admin/reassign-managers'
      preLoaderRoute: typeof AdminReassignManagersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll-settings': {
      id: '/admin/payroll-settings'
      path: '/payroll-settings'
      fullPath: '/admin/payroll-settings'
      preLoaderRoute: typeof AdminPayrollSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org-chart': {
      id: '/admin/org-chart'
      path: '/org-chart'
      fullPath: '/admin/org-chart'
      preLoaderRoute: typeof AdminOrgChartRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notification-preferences': {
      id: '/admin/notification-preferences'
      path: '/notification-preferences'
      fullPath: '/admin/notification-preferences'
      preLoaderRoute: typeof AdminNotificationPreferencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/networks': {
      id: '/admin/networks'
      path: '/networks'
      fullPath: '/admin/networks'
      preLoaderRoute: typeof AdminNetworksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaves-requests': {
      id: '/admin/leaves-requests'
      path: '/leaves-requests'
      fullPath: '/admin/leaves-requests'
      preLoaderRoute: typeof AdminLeavesRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaves': {
      id: '/admin/leaves'
      path: '/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AdminLeavesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/late-penalties': {
      id: '/admin/late-penalties'
      path: '/late-penalties'
      fullPath: '/admin/late-penalties'
      preLoaderRoute: typeof AdminLatePenaltiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpis': {
      id: '/admin/kpis'
      path: '/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AdminKpisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/holidays': {
      id: '/admin/holidays'
      path: '/holidays'
      fullPath: '/admin/holidays'
      preLoaderRoute: typeof AdminHolidaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geofencing': {
      id: '/admin/geofencing'
      path: '/geofencing'
      fullPath: '/admin/geofencing'
      preLoaderRoute: typeof AdminGeofencingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employee-access': {
      id: '/admin/employee-access'
      path: '/employee-access'
      fullPath: '/admin/employee-access'
      preLoaderRoute: typeof AdminEmployeeAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allowances': {
      id: '/admin/allowances'
      path: '/allowances'
      fullPath: '/admin/allowances'
      preLoaderRoute: typeof AdminAllowancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/'
      fullPath: '/admin/employees/'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/admin/employees/$id': {
      id: '/admin/employees/$id'
      path: '/$id'
      fullPath: '/admin/employees/$id'
      preLoaderRoute: typeof AdminEmployeesIdRouteImport
      parentRoute: typeof AdminEmployeesRoute
    }
    '/api/public/cron/run-schedules': {
      id: '/api/public/cron/run-schedules'
      path: '/api/public/cron/run-schedules'
      fullPath: '/api/public/cron/run-schedules'
      preLoaderRoute: typeof ApiPublicCronRunSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminEmployeesRouteChildren {
  AdminEmployeesIdRoute: typeof AdminEmployeesIdRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
}

const AdminEmployeesRouteChildren: AdminEmployeesRouteChildren = {
  AdminEmployeesIdRoute: AdminEmployeesIdRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
}

const AdminEmployeesRouteWithChildren = AdminEmployeesRoute._addFileChildren(
  AdminEmployeesRouteChildren,
)

interface AdminRouteChildren {
  AdminAllowancesRoute: typeof AdminAllowancesRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminEmployeeAccessRoute: typeof AdminEmployeeAccessRoute
  AdminEmployeesRoute: typeof AdminEmployeesRouteWithChildren
  AdminGeofencingRoute: typeof AdminGeofencingRoute
  AdminHolidaysRoute: typeof AdminHolidaysRoute
  AdminKpisRoute: typeof AdminKpisRoute
  AdminLatePenaltiesRoute: typeof AdminLatePenaltiesRoute
  AdminLeavesRoute: typeof AdminLeavesRoute
  AdminLeavesRequestsRoute: typeof AdminLeavesRequestsRoute
  AdminNetworksRoute: typeof AdminNetworksRoute
  AdminNotificationPreferencesRoute: typeof AdminNotificationPreferencesRoute
  AdminOrgChartRoute: typeof AdminOrgChartRoute
  AdminPayrollRoute: typeof AdminPayrollRoute
  AdminPayrollSettingsRoute: typeof AdminPayrollSettingsRoute
  AdminReassignManagersRoute: typeof AdminReassignManagersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShiftsRoute: typeof AdminShiftsRoute
  AdminTargetsOvertimeRoute: typeof AdminTargetsOvertimeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllowancesRoute: AdminAllowancesRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminEmployeeAccessRoute: AdminEmployeeAccessRoute,
  AdminEmployeesRoute: AdminEmployeesRouteWithChildren,
  AdminGeofencingRoute: AdminGeofencingRoute,
  AdminHolidaysRoute: AdminHolidaysRoute,
  AdminKpisRoute: AdminKpisRoute,
  AdminLatePenaltiesRoute: AdminLatePenaltiesRoute,
  AdminLeavesRoute: AdminLeavesRoute,
  AdminLeavesRequestsRoute: AdminLeavesRequestsRoute,
  AdminNetworksRoute: AdminNetworksRoute,
  AdminNotificationPreferencesRoute: AdminNotificationPreferencesRoute,
  AdminOrgChartRoute: AdminOrgChartRoute,
  AdminPayrollRoute: AdminPayrollRoute,
  AdminPayrollSettingsRoute: AdminPayrollSettingsRoute,
  AdminReassignManagersRoute: AdminReassignManagersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShiftsRoute: AdminShiftsRoute,
  AdminTargetsOvertimeRoute: AdminTargetsOvertimeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeRouteChildren {
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeBiometricsRoute: typeof EmployeeBiometricsRoute
  EmployeeCheckRoute: typeof EmployeeCheckRoute
  EmployeeLeavesRoute: typeof EmployeeLeavesRoute
  EmployeeMessagesRoute: typeof EmployeeMessagesRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeTasksRoute: typeof EmployeeTasksRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeBiometricsRoute: EmployeeBiometricsRoute,
  EmployeeCheckRoute: EmployeeCheckRoute,
  EmployeeLeavesRoute: EmployeeLeavesRoute,
  EmployeeMessagesRoute: EmployeeMessagesRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeTasksRoute: EmployeeTasksRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface ManagerRouteChildren {
  ManagerCheckRoute: typeof ManagerCheckRoute
  ManagerProfileRoute: typeof ManagerProfileRoute
  ManagerTasksRoute: typeof ManagerTasksRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  ManagerTripsRoute: typeof ManagerTripsRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerCheckRoute: ManagerCheckRoute,
  ManagerProfileRoute: ManagerProfileRoute,
  ManagerTasksRoute: ManagerTasksRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  ManagerTripsRoute: ManagerTripsRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

interface StaffRouteChildren {
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffLeavesRoute: typeof StaffLeavesRoute
  StaffProfileRoute: typeof StaffProfileRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffLeavesRoute: StaffLeavesRoute,
  StaffProfileRoute: StaffProfileRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  ApiPublicCronRunSchedulesRoute: ApiPublicCronRunSchedulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
